name: "Prune Pre-Release Tags"
description: "Removes old pre-release Git tags, keeping only the latest N. Never removes stable release tags."

inputs:
  keep-count:
    description: "Number of most recent pre-release tags to keep per branch"
    required: false
    default: "10"
  dry-run:
    description: "Preview what would be deleted without actually deleting (true/false)"
    required: false
    default: "false"
  push:
    description: "Whether to push deletions to remote (true/false)"
    required: false
    default: "true"

outputs:
  deleted-count:
    description: "Number of tags deleted (or would be deleted in dry-run)"
    value: ${{ steps.prune.outputs.deleted-count }}
  deleted-tags:
    description: "Comma-separated list of deleted tag names"
    value: ${{ steps.prune.outputs.deleted-tags }}
  kept-count:
    description: "Number of pre-release tags kept"
    value: ${{ steps.prune.outputs.kept-count }}

runs:
  using: "composite"
  steps:
    - name: Prune Pre-Release Tags
      id: prune
      shell: bash
      env:
        KEEP_COUNT: ${{ inputs.keep-count }}
        DRY_RUN: ${{ inputs.dry-run }}
        PUSH: ${{ inputs.push }}
      run: |
        set -euo pipefail

        # Validate inputs
        echo "🔍 Validating inputs..."
        if [[ ! "$KEEP_COUNT" =~ ^[0-9]+$ ]]; then
          echo "❌ ERROR: Invalid keep-count '$KEEP_COUNT'. Must be a positive integer."
          exit 1
        fi

        if [[ ! "$DRY_RUN" =~ ^(true|false)$ ]]; then
          echo "❌ ERROR: Invalid dry-run value '$DRY_RUN'. Must be 'true' or 'false'."
          exit 1
        fi

        if [[ ! "$PUSH" =~ ^(true|false)$ ]]; then
          echo "❌ ERROR: Invalid push value '$PUSH'. Must be 'true' or 'false'."
          exit 1
        fi

        # Fetch all tags from remote
        echo "📥 Fetching tags from remote..."
        git fetch --tags --prune --quiet || echo "⚠️  Could not fetch tags"

        # Get all tags sorted by creation date (newest first)
        echo "🔍 Analyzing tags..."
        
        # Pre-release pattern: vX.Y.Z-{anything} or X.Y.Z-{anything} (e.g., v1.2.3-alpha.1, 1.2.3-dev.20241030)
        # Stable release pattern: vX.Y.Z or X.Y.Z (no suffix)
        
        STABLE_TAGS=()
        PRERELEASE_TAGS=()

        # Read all tags into arrays
        while IFS= read -r tag; do
          if [[ -z "$tag" ]]; then
            continue
          fi
          
          # Check if it's a semver tag
          if [[ "$tag" =~ ^v?(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$ ]]; then
            # Stable release (no suffix)
            STABLE_TAGS+=("$tag")
          elif [[ "$tag" =~ ^v?(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)- ]]; then
            # Pre-release (has suffix after dash)
            PRERELEASE_TAGS+=("$tag")
          fi
          fi
        done < <(git tag --sort=-creatordate)

        echo ""
        echo "📊 Tag Summary:"
        echo "   Stable releases: ${#STABLE_TAGS[@]}"
        echo "   Pre-releases: ${#PRERELEASE_TAGS[@]}"
        echo "   Keeping latest: $KEEP_COUNT pre-releases"
        echo ""

        # Determine which pre-release tags to delete
        TAGS_TO_DELETE=()
        TAGS_TO_KEEP=()

        COUNT=0
        for tag in "${PRERELEASE_TAGS[@]}"; do
          if [[ $COUNT -lt $KEEP_COUNT ]]; then
            TAGS_TO_KEEP+=("$tag")
            ((COUNT++))
          else
            TAGS_TO_DELETE+=("$tag")
          fi
        done

        echo "✅ Pre-release tags to keep (${#TAGS_TO_KEEP[@]}):"
        if [[ ${#TAGS_TO_KEEP[@]} -eq 0 ]]; then
          echo "   (none)"
        else
          for tag in "${TAGS_TO_KEEP[@]}"; do
            echo "   - $tag"
          done
        fi

        echo ""
        echo "🗑️  Pre-release tags to delete (${#TAGS_TO_DELETE[@]}):"
        if [[ ${#TAGS_TO_DELETE[@]} -eq 0 ]]; then
          echo "   (none)"
        else
          for tag in "${TAGS_TO_DELETE[@]}"; do
            echo "   - $tag"
          done
        fi

        echo ""
        echo "🛡️  Stable releases (never deleted):"
        if [[ ${#STABLE_TAGS[@]} -eq 0 ]]; then
          echo "   (none)"
        else
          for tag in "${STABLE_TAGS[@]}"; do
            echo "   - $tag"
          done
        fi

        # Delete tags if not in dry-run mode
        DELETED_COUNT=0
        DELETED_TAG_LIST=""

        if [[ ${#TAGS_TO_DELETE[@]} -gt 0 ]]; then
          if [[ "$DRY_RUN" == "true" ]]; then
            echo ""
            echo "🔍 DRY RUN: Would delete ${#TAGS_TO_DELETE[@]} tags"
            DELETED_COUNT=${#TAGS_TO_DELETE[@]}
            DELETED_TAG_LIST=$(IFS=,; echo "${TAGS_TO_DELETE[*]}")
          else
            echo ""
            echo "🗑️  Deleting ${#TAGS_TO_DELETE[@]} pre-release tags..."
            
            for tag in "${TAGS_TO_DELETE[@]}"; do
              # Delete local tag
              if git tag -d "$tag" >/dev/null 2>&1; then
                echo "   ✓ Deleted local: $tag"
                ((DELETED_COUNT++))
                
                if [[ -z "$DELETED_TAG_LIST" ]]; then
                  DELETED_TAG_LIST="$tag"
                else
                  DELETED_TAG_LIST="$DELETED_TAG_LIST,$tag"
                fi
              else
                echo "   ⚠️  Could not delete local tag: $tag"
              fi
            done

            # Push deletions to remote if requested
            if [[ "$PUSH" == "true" && $DELETED_COUNT -gt 0 ]]; then
              echo ""
              echo "📤 Pushing deletions to remote..."
              
              FAILED_DELETIONS=()
              
              for tag in "${TAGS_TO_DELETE[@]}"; do
                # Try to delete from remote
                if git push origin ":refs/tags/$tag" >/dev/null 2>&1; then
                  echo "   ✓ Deleted remote: $tag"
                else
                  echo "   ⚠️  Could not delete remote tag: $tag"
                  FAILED_DELETIONS+=("$tag")
                fi
              done

              if [[ ${#FAILED_DELETIONS[@]} -gt 0 ]]; then
                echo ""
                echo "⚠️  Failed to delete ${#FAILED_DELETIONS[@]} remote tags:"
                for tag in "${FAILED_DELETIONS[@]}"; do
                  echo "   - $tag"
                done
                echo ""
                echo "   You can manually delete them with:"
                for tag in "${FAILED_DELETIONS[@]}"; do
                  echo "   git push origin :refs/tags/$tag"
                done
              fi
            else
              if [[ "$PUSH" != "true" ]]; then
                echo "⏭️  Skipping remote deletion (push=false)"
              fi
            fi
          fi
        else
          echo ""
          echo "✅ No pre-release tags to delete"
        fi

        # Set outputs
        echo "deleted-count=$DELETED_COUNT" >> "$GITHUB_OUTPUT"
        echo "deleted-tags=$DELETED_TAG_LIST" >> "$GITHUB_OUTPUT"
        echo "kept-count=${#TAGS_TO_KEEP[@]}" >> "$GITHUB_OUTPUT"

        # Summary
        echo ""
        echo "📊 Cleanup Summary:"
        echo "   Pre-releases kept: ${#TAGS_TO_KEEP[@]}"
        echo "   Pre-releases deleted: $DELETED_COUNT"
        echo "   Stable releases protected: ${#STABLE_TAGS[@]}"

        if [[ "$DRY_RUN" == "true" ]]; then
          echo ""
          echo "🔍 This was a DRY RUN - no tags were actually deleted"
          echo "   Set dry-run: false to perform actual deletion"
        fi
