name: "Build App"
description: "Builds and pushes a single-architecture container image for an application"

inputs:
  app:
    description: "Application name (e.g., authd, api, worker)"
    required: true
  arch:
    description: "Target architecture (amd64 or arm64)"
    required: true
  semver:
    description: "Semantic version tag (e.g., v1.2.3 or 1.2.3-alpha.1). Leading 'v' is optional."
    required: true
  registry:
    description: "Container registry URL (e.g., ghcr.io)"
    required: true
  org:
    description: "Organization or namespace in the registry (e.g., hydn-co)"
    required: true
  image-prefix:
    description: "Prefix for image name (e.g., mesh-, liteiga-). Use empty string for no prefix."
    required: false
    default: "mesh-"
  branch:
    description: "Branch name for additional tag. Empty = GITHUB_REF_NAME; '-' = skip."
    required: false
    default: ""
  dockerfile-path:
    description: "Path to Dockerfile. Use {app} as placeholder."
    required: false
    default: "cmd/{app}/Dockerfile"
  build-context:
    description: "Docker build context directory"
    required: false
    default: "."

outputs:
  image:
    value: ${{ steps.outputs.outputs.image }}
  image-branch:
    value: ${{ steps.outputs.outputs.image_branch }}
  digest:
    value: ${{ steps.outputs.outputs.digest }}
  exists:
    value: ${{ steps.outputs.outputs.exists }}

runs:
  using: "composite"
  steps:
    - name: Prepare
      id: prepare
      shell: bash
      env:
        IMAGE: ${{ format('{0}/{1}/{2}{3}', inputs.registry, inputs.org, inputs.image-prefix, inputs.app) }}
        IMAGE_REF: ${{ format('{0}/{1}/{2}{3}:{4}-{5}', inputs.registry, inputs.org, inputs.image-prefix, inputs.app, inputs.semver, inputs.arch) }}
        BRANCH_INPUT: ${{ inputs.branch }}
        ARCH: ${{ inputs.arch }}
        APP: ${{ inputs.app }}
        DOCKERFILE_PATH: ${{ inputs.dockerfile-path }}
        BUILD_CONTEXT: ${{ inputs.build-context }}
      run: |
        [[ "${{ inputs.arch }}" =~ ^(amd64|arm64)$ ]] || { echo "ERROR: Invalid arch"; exit 1; }
        [[ "${{ inputs.semver }}" =~ ^v?(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?(\+([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?$ ]] || { echo "ERROR: Invalid semver"; exit 1; }
        test -f "${DOCKERFILE_PATH//\{app\}/$APP}" || { echo "ERROR: Dockerfile not found"; exit 1; }
        B="${BRANCH_INPUT:-$GITHUB_REF_NAME}"; [[ "$BRANCH_INPUT" == "-" || -z "$B" ]] && BT="" || { BT="${B//\//-}"; BT="${BT//[^a-zA-Z0-9_.-]/-}"; BT="${BT:0:128}-$ARCH"; }
        docker buildx use buildx-registry-cache 2>/dev/null || docker buildx create --use --name buildx-registry-cache --driver docker-container
        docker buildx inspect --bootstrap
        docker manifest inspect "$IMAGE_REF" >/dev/null 2>&1 && echo "semver_exists=true" >> "$GITHUB_OUTPUT" || echo "semver_exists=false" >> "$GITHUB_OUTPUT"
        echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
        echo "image_ref=$IMAGE_REF" >> "$GITHUB_OUTPUT"
        echo "branch_tag=$BT" >> "$GITHUB_OUTPUT"
        echo "dockerfile=${DOCKERFILE_PATH//\{app\}/$APP}" >> "$GITHUB_OUTPUT"
        echo "build_context=$BUILD_CONTEXT" >> "$GITHUB_OUTPUT"
        echo "cache_from=type=registry,ref=$IMAGE:buildcache" >> "$GITHUB_OUTPUT"
        echo "cache_to=type=registry,ref=$IMAGE:buildcache,mode=max" >> "$GITHUB_OUTPUT"

    - name: Build image
      if: steps.prepare.outputs.semver_exists != 'true'
      shell: bash
      env:
        IMAGE_REF: ${{ steps.prepare.outputs.image_ref }}
        IMAGE: ${{ steps.prepare.outputs.image }}
        BRANCH_TAG: ${{ steps.prepare.outputs.branch_tag }}
        DOCKERFILE: ${{ steps.prepare.outputs.dockerfile }}
        BUILD_CONTEXT: ${{ steps.prepare.outputs.build_context }}
        SEMVER: ${{ inputs.semver }}
        CACHE_FROM: ${{ steps.prepare.outputs.cache_from }}
        CACHE_TO: ${{ steps.prepare.outputs.cache_to }}
      run: |
        [ -n "$BRANCH_TAG" ] && docker pull "$IMAGE:$BRANCH_TAG" 2>/dev/null || true
        docker buildx build -f "$DOCKERFILE" --build-arg "SEMVER=$SEMVER" --cache-from "$CACHE_FROM" $([ -n "$BRANCH_TAG" ] && echo "--cache-from $IMAGE:$BRANCH_TAG") --cache-to "$CACHE_TO" --tag "$IMAGE_REF" $([ -n "$BRANCH_TAG" ] && echo "--tag $IMAGE:$BRANCH_TAG") --push "$BUILD_CONTEXT"

    - name: Push branch tag
      if: steps.prepare.outputs.branch_tag != ''
      shell: bash
      env:
        IMAGE_REF: ${{ steps.prepare.outputs.image_ref }}
        IMAGE: ${{ steps.prepare.outputs.image }}
        BRANCH_TAG: ${{ steps.prepare.outputs.branch_tag }}
      run: |
        REF=$(docker manifest inspect "$IMAGE_REF" | jq -r '.manifests[0].digest // .config.digest // empty')
        CUR=$(docker manifest inspect "$IMAGE:$BRANCH_TAG" 2>/dev/null | jq -r '.manifests[0].digest // .config.digest // empty' || echo "")
        [ "$CUR" != "$REF" ] && docker buildx imagetools create --tag "$IMAGE:$BRANCH_TAG" "$IMAGE_REF" --push

    - name: Set outputs
      id: outputs
      shell: bash
      env:
        IMAGE_REF: ${{ steps.prepare.outputs.image_ref }}
        IMAGE: ${{ steps.prepare.outputs.image }}
        BRANCH_TAG: ${{ steps.prepare.outputs.branch_tag }}
        SEMVER_EXISTS: ${{ steps.prepare.outputs.semver_exists }}
      run: |
        echo "image=$IMAGE_REF" >> "$GITHUB_OUTPUT"
        echo "image_branch=$([ -n "$BRANCH_TAG" ] && echo "$IMAGE:$BRANCH_TAG" || echo "")" >> "$GITHUB_OUTPUT"
        echo "digest=$(docker manifest inspect "$IMAGE_REF" 2>/dev/null | jq -r '.manifests[0].digest // .config.digest // empty' || echo "")" >> "$GITHUB_OUTPUT"
        echo "exists=$SEMVER_EXISTS" >> "$GITHUB_OUTPUT"
