name: "Build App"
description: "Builds and pushes a single-architecture container image for an application"

inputs:
  app:
    description: "Application name (e.g., authd, api, worker)"
    required: true
  arch:
    description: "Target architecture (amd64 or arm64)"
    required: true
  semver:
    description: "Semantic version tag (e.g., v1.2.3 or 1.2.3-alpha.1). Leading 'v' is optional."
    required: true
  registry:
    description: "Container registry URL (e.g., ghcr.io)"
    required: true
  org:
    description: "Organization or namespace in the registry (e.g., hydn-co)"
    required: true
  image-prefix:
    description: "Prefix for image name (e.g., mesh-, liteiga-). Use empty string for no prefix."
    required: false
    default: "mesh-"
  branch:
    description: "Branch name for additional tag (e.g. main, feature/foo). Empty = use GITHUB_REF_NAME; set to '-' to skip branch tag."
    required: false
    default: ""
  dockerfile-path:
    description: "Path to Dockerfile relative to repository root (e.g., cmd/{app}/Dockerfile or backend/cmd/{app}/Dockerfile). Use {app} as placeholder."
    required: false
    default: "cmd/{app}/Dockerfile"
  build-context:
    description: "Docker build context directory"
    required: false
    default: "."

outputs:
  image:
    description: "Full image reference (registry/org/prefix-app:semver-arch)"
    value: ${{ steps.build.outputs.image }}
  image-branch:
    description: "Image reference with branch tag when branch tagging is used (registry/org/prefix-app:branch-arch)"
    value: ${{ steps.build.outputs.image_branch }}
  digest:
    description: "Image digest (sha256:...)"
    value: ${{ steps.build.outputs.digest }}
  exists:
    description: "Whether image already existed (true/false)"
    value: ${{ steps.build.outputs.exists }}

runs:
  using: "composite"
  steps:
    - name: Build and Push ${{ inputs.app }} (${{ inputs.arch }})
      id: build
      shell: bash
      env:
        APP: ${{ inputs.app }}
        IMAGE_PREFIX: ${{ inputs.image-prefix }}
        REGISTRY: ${{ inputs.registry }}
        ORG: ${{ inputs.org }}
        ARCH: ${{ inputs.arch }}
        SEMVER: ${{ inputs.semver }}
        DOCKERFILE_PATH: ${{ inputs.dockerfile-path }}
        BUILD_CONTEXT: ${{ inputs.build-context }}
        BRANCH_INPUT: ${{ inputs.branch }}
      run: |
        set -euo pipefail

        # Validate inputs
        echo " Validating inputs..."
        if [[ ! "$ARCH" =~ ^(amd64|arm64)$ ]]; then
          echo " ERROR: Invalid architecture '\''$ARCH'\''. Must be '\''amd64'\'' or '\''arm64'\''."
          exit 1
        fi

        # Accept semver with optional leading 'v' and optional prerelease/build metadata
        # Examples: v1.2.3, 1.2.3, 0.2.0-alpha.389, v1.2.3+build.123
        if [[ ! "$SEMVER" =~ ^v?(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?(\+([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?$ ]]; then
          echo " ERROR: Invalid semver format '\''$SEMVER'\''. Expected a semantic version like 'v1.2.3' or '1.2.3-alpha.1'"
          exit 1
        fi

        # Resolve Dockerfile path (replace {app} placeholder)
        DOCKERFILE="${DOCKERFILE_PATH//\{app\}/$APP}"

        # Verify Dockerfile exists
        if [[ ! -f "$DOCKERFILE" ]]; then
          echo " ERROR: Dockerfile not found at $DOCKERFILE"
          echo "   Current directory: $(pwd)"
          echo "   Looking for: $DOCKERFILE"
          echo "   Available directories:"
          ls -la 2>/dev/null || echo "   (unable to list)"
          exit 1
        fi

        # Construct image name
        IMAGE="$REGISTRY/$ORG/${IMAGE_PREFIX}${APP}"
        IMAGE_REF="$IMAGE:$SEMVER-$ARCH"

        # Branch tag: optional second tag (branch-arch). Use input or GITHUB_REF_NAME; skip if input is '-'
        BRANCH_TAG=""
        if [[ "$BRANCH_INPUT" != "-" ]]; then
          BRANCH="${BRANCH_INPUT:-$GITHUB_REF_NAME}"
          if [[ -n "$BRANCH" ]]; then
            BRANCH_SANITIZED="${BRANCH//\//-}"
            BRANCH_SANITIZED="${BRANCH_SANITIZED//[^a-zA-Z0-9_.-]/-}"
            BRANCH_SANITIZED="${BRANCH_SANITIZED:0:128}"
            [[ -n "$BRANCH_SANITIZED" ]] && BRANCH_TAG="${BRANCH_SANITIZED}-${ARCH}"
          fi
        fi

        # Use stable buildcache ref for layer reuse across version-only changes
        CACHE_REF="type=registry,ref=$IMAGE:buildcache"
        CACHE_FROM="$CACHE_REF"
        CACHE_TO="${CACHE_REF},mode=max"

        echo " Checking if $IMAGE_REF exists in registry..."

        MANIFEST_JSON=$(docker manifest inspect "$IMAGE_REF" 2>/dev/null) || true
        if [[ -n "$MANIFEST_JSON" ]]; then
          echo " Image $IMAGE_REF already exists, skipping build."

          # Get digest from manifest once
          DIGEST=$(echo "$MANIFEST_JSON" | jq -r '.manifests[0].digest // .config.digest // empty' 2>/dev/null || echo "")
          REF_DIGEST="$DIGEST"

          # Add branch tag only if missing or pointing to a different image (avoid redundant push)
          if [[ -n "$BRANCH_TAG" ]]; then
            BRANCH_REF="$IMAGE:$BRANCH_TAG"
            BRANCH_JSON=$(docker manifest inspect "$BRANCH_REF" 2>/dev/null) || true
            CURRENT_DIGEST=""
            [[ -n "$BRANCH_JSON" ]] && CURRENT_DIGEST=$(echo "$BRANCH_JSON" | jq -r '.manifests[0].digest // .config.digest // empty' 2>/dev/null || echo "")
            if [[ -z "$CURRENT_DIGEST" || "$CURRENT_DIGEST" != "$REF_DIGEST" ]]; then
              echo " Tagging existing image as $BRANCH_REF"
              docker buildx imagetools create --tag "$BRANCH_REF" "$IMAGE_REF" --push
            else
              echo " Branch tag $BRANCH_REF already up to date, skipping push"
            fi
          fi

          # Set outputs
          echo "image=$IMAGE_REF" >> "$GITHUB_OUTPUT"
          echo "image_branch=$([ -n "$BRANCH_TAG" ] && echo "$IMAGE:$BRANCH_TAG" || echo "")" >> "$GITHUB_OUTPUT"
          echo "digest=$DIGEST" >> "$GITHUB_OUTPUT"
          echo "exists=true" >> "$GITHUB_OUTPUT"
        else
          echo " Building $IMAGE_REF from $DOCKERFILE"
          echo "   Build context: $BUILD_CONTEXT"

          # Prepare build arguments
          BUILD_ARGS=(
            "-f" "$DOCKERFILE"
            "--build-arg" "SEMVER=$SEMVER"
            "--tag" "$IMAGE_REF"
            "--push"
          )
          if [[ -n "$BRANCH_TAG" ]]; then
            BUILD_ARGS+=("--tag" "$IMAGE:$BRANCH_TAG")
            echo "   Branch tag: $IMAGE:$BRANCH_TAG"
          fi

          # Add cache: branch image first, then buildcache
          if [[ -n "$BRANCH_TAG" ]]; then
            BRANCH_CACHE_REF="type=registry,ref=$IMAGE:$BRANCH_TAG"
            echo " Using branch image as cache: $BRANCH_CACHE_REF"
            BUILD_ARGS+=("--cache-from" "$BRANCH_CACHE_REF")
          fi
          echo " Using build cache from: $CACHE_FROM"
          BUILD_ARGS+=("--cache-from" "$CACHE_FROM")
          echo " Exporting build cache to: $CACHE_TO"
          BUILD_ARGS+=("--cache-to" "$CACHE_TO")

          # Build with retry logic (3 attempts)
          MAX_ATTEMPTS=3
          ATTEMPT=1

          while [[ $ATTEMPT -le $MAX_ATTEMPTS ]]; do
            echo " Build attempt $ATTEMPT/$MAX_ATTEMPTS..."

            if docker buildx build "${BUILD_ARGS[@]}" "$BUILD_CONTEXT"; then
              echo " Successfully built and pushed $IMAGE_REF"
              if [[ -n "$BRANCH_TAG" ]]; then
                echo " Also pushed $IMAGE:$BRANCH_TAG"
              fi

              # Get image digest
              DIGEST=$(docker buildx imagetools inspect "$IMAGE_REF" --format '{{json .Manifest}}' | jq -r '.digest // empty' 2>/dev/null || echo "")

              # Set outputs
              echo "image=$IMAGE_REF" >> "$GITHUB_OUTPUT"
              echo "image_branch=$([ -n "$BRANCH_TAG" ] && echo "$IMAGE:$BRANCH_TAG" || echo "")" >> "$GITHUB_OUTPUT"
              echo "digest=$DIGEST" >> "$GITHUB_OUTPUT"
              echo "exists=false" >> "$GITHUB_OUTPUT"

              exit 0
            else
              if [[ $ATTEMPT -lt $MAX_ATTEMPTS ]]; then
                echo "  Build failed, retrying in 10 seconds..."
                sleep 10
                ((ATTEMPT++))
              else
                echo " ERROR: Docker build failed after $MAX_ATTEMPTS attempts"
                echo "   Image: $IMAGE_REF"
                echo "   Dockerfile: $DOCKERFILE"
                echo "   Build context: $BUILD_CONTEXT"
                echo "   Build arg SEMVER: $SEMVER"
                exit 1
              fi
            fi
          done
        fi
