name: "Build App"
description: "Builds and pushes a single-architecture container image for an application"

inputs:
  app:
    description: "Application name (e.g., authd, api, worker)"
    required: true
  arch:
    description: "Target architecture (amd64 or arm64)"
    required: true
  semver:
    description: "Semantic version tag (e.g., v1.2.3 or 1.2.3-alpha.1). Leading 'v' is optional."
    required: true
  registry:
    description: "Container registry URL (e.g., ghcr.io)"
    required: true
  org:
    description: "Organization or namespace in the registry (e.g., hydn-co)"
    required: true
  image-prefix:
    description: "Prefix for image name (e.g., mesh-, liteiga-). Use empty string for no prefix."
    required: false
    default: "mesh-"
  branch:
    description: "Branch name for additional tag. Empty = GITHUB_REF_NAME; '-' = skip."
    required: false
    default: ""
  dockerfile-path:
    description: "Path to Dockerfile. Use {app} as placeholder."
    required: false
    default: "cmd/{app}/Dockerfile"
  build-context:
    description: "Docker build context directory"
    required: false
    default: "."

outputs:
  image:
    value: ${{ steps.outputs.outputs.image }}
  image-branch:
    value: ${{ steps.outputs.outputs.image_branch }}
  digest:
    value: ${{ steps.outputs.outputs.digest }}
  exists:
    value: ${{ steps.outputs.outputs.exists }}

runs:
  using: "composite"
  steps:
    - name: Prepare
      id: prepare
      shell: bash
      env:
        IMAGE: ${{ format('{0}/{1}/{2}{3}', inputs.registry, inputs.org, inputs.image-prefix, inputs.app) }}
        IMAGE_REF: ${{ format('{0}/{1}/{2}{3}:{4}-{5}', inputs.registry, inputs.org, inputs.image-prefix, inputs.app, inputs.semver, inputs.arch) }}
        BRANCH_INPUT: ${{ inputs.branch }}
        ARCH: ${{ inputs.arch }}
        APP: ${{ inputs.app }}
        DOCKERFILE_PATH: ${{ inputs.dockerfile-path }}
        BUILD_CONTEXT: ${{ inputs.build-context }}
      run: |
        [[ "${{ inputs.arch }}" =~ ^(amd64|arm64)$ ]] || { echo "ERROR: Invalid arch"; exit 1; }
        [[ "${{ inputs.semver }}" =~ ^v?(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?(\+([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?$ ]] || { echo "ERROR: Invalid semver"; exit 1; }
        test -f "${DOCKERFILE_PATH//\{app\}/$APP}" || { echo "ERROR: Dockerfile not found"; exit 1; }
        B="${BRANCH_INPUT:-$GITHUB_REF_NAME}"; [[ "$BRANCH_INPUT" == "-" || -z "$B" ]] && BT="" || { BT="${B//\//-}"; BT="${BT//[^a-zA-Z0-9_.-]/-}"; BT="${BT:0:128}-$ARCH"; }
        docker buildx use buildx-registry-cache 2>/dev/null || docker buildx create --use --name buildx-registry-cache --driver docker-container
        docker buildx inspect --bootstrap
        MANIFEST=$(docker manifest inspect "$IMAGE_REF" 2>/dev/null) || true
        if [ -n "$MANIFEST" ]; then
          echo "semver_exists=true" >> "$GITHUB_OUTPUT"
          echo "image_digest=$(echo "$MANIFEST" | jq -r '.manifests[0].digest // .config.digest // empty')" >> "$GITHUB_OUTPUT"
        else
          echo "semver_exists=false" >> "$GITHUB_OUTPUT"
          echo "image_digest=" >> "$GITHUB_OUTPUT"
        fi
        echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
        echo "image_ref=$IMAGE_REF" >> "$GITHUB_OUTPUT"
        echo "branch_tag=$BT" >> "$GITHUB_OUTPUT"
        echo "dockerfile=${DOCKERFILE_PATH//\{app\}/$APP}" >> "$GITHUB_OUTPUT"
        echo "build_context=$BUILD_CONTEXT" >> "$GITHUB_OUTPUT"

    - name: Build image
      id: build
      if: steps.prepare.outputs.semver_exists != 'true'
      shell: bash
      env:
        IMAGE_REF: ${{ steps.prepare.outputs.image_ref }}
        IMAGE: ${{ steps.prepare.outputs.image }}
        BRANCH_TAG: ${{ steps.prepare.outputs.branch_tag }}
        DOCKERFILE: ${{ steps.prepare.outputs.dockerfile }}
        BUILD_CONTEXT: ${{ steps.prepare.outputs.build_context }}
        SEMVER: ${{ inputs.semver }}
      run: |
        set -e
        [ -n "$BRANCH_TAG" ] && docker pull "$IMAGE:$BRANCH_TAG" 2>/dev/null || true
        docker buildx build -f "$DOCKERFILE" --build-arg "SEMVER=$SEMVER" \
          $([ -n "$BRANCH_TAG" ] && echo "--cache-from type=registry,ref=$IMAGE:$BRANCH_TAG") \
          $([ -n "$BRANCH_TAG" ] && echo "--cache-to type=registry,ref=$IMAGE:$BRANCH_TAG,mode=max") \
          --tag "$IMAGE_REF" $([ -n "$BRANCH_TAG" ] && echo "--tag $IMAGE:$BRANCH_TAG") --push "$BUILD_CONTEXT" 2>&1 | tee /tmp/build.log
        [ ${PIPESTATUS[0]} -eq 0 ]
        DIGEST=$(grep "naming to" /tmp/build.log 2>/dev/null | tail -1 | grep -oE 'sha256:[a-f0-9]{64}' | tail -1)
        [ -z "$DIGEST" ] && DIGEST=$(grep -oE 'sha256:[a-f0-9]{64}' /tmp/build.log | tail -1)
        echo "digest=${DIGEST}" >> "$GITHUB_OUTPUT"

    - name: Push branch tag
      if: steps.prepare.outputs.branch_tag != '' && (steps.prepare.outputs.semver_exists == 'true' || steps.build.outcome == 'success')
      shell: bash
      continue-on-error: true
      timeout-minutes: 2
      env:
        IMAGE_REF: ${{ steps.prepare.outputs.image_ref }}
        IMAGE: ${{ steps.prepare.outputs.image }}
        BRANCH_TAG: ${{ steps.prepare.outputs.branch_tag }}
        REF: ${{ steps.prepare.outputs.semver_exists == 'true' && steps.prepare.outputs.image_digest || steps.build.outputs.digest }}
      run: |
        [ -z "$REF" ] && REF=$(docker manifest inspect "$IMAGE_REF" 2>/dev/null | jq -r '.manifests[0].digest // .config.digest // empty')
        [ -z "$REF" ] && exit 0
        CUR=$(docker manifest inspect "$IMAGE:$BRANCH_TAG" 2>/dev/null | jq -r '.manifests[0].digest // .config.digest // empty' || echo "")
        [ "$CUR" != "$REF" ] && docker buildx imagetools create --tag "$IMAGE:$BRANCH_TAG" "$IMAGE_REF" --push

    - name: Set outputs
      id: outputs
      if: always() && steps.prepare.outcome == 'success'
      shell: bash
      env:
        IMAGE_REF: ${{ steps.prepare.outputs.image_ref }}
        IMAGE: ${{ steps.prepare.outputs.image }}
        BRANCH_TAG: ${{ steps.prepare.outputs.branch_tag }}
        SEMVER_EXISTS: ${{ steps.prepare.outputs.semver_exists }}
        DIGEST: ${{ steps.prepare.outputs.semver_exists == 'true' && steps.prepare.outputs.image_digest || steps.build.outputs.digest }}
      run: |
        echo "image=$IMAGE_REF" >> "$GITHUB_OUTPUT"
        echo "image_branch=$([ -n "$BRANCH_TAG" ] && echo "$IMAGE:$BRANCH_TAG" || echo "")" >> "$GITHUB_OUTPUT"
        if [ -n "$DIGEST" ]; then
          echo "digest=$DIGEST" >> "$GITHUB_OUTPUT"
        else
          echo "digest=$(docker manifest inspect "$IMAGE_REF" 2>/dev/null | jq -r '.manifests[0].digest // .config.digest // empty' || echo "")" >> "$GITHUB_OUTPUT"
        fi
        echo "exists=$SEMVER_EXISTS" >> "$GITHUB_OUTPUT"
