name: "Build App"
description: "Builds and pushes a single-architecture container image for an application"

inputs:
  app:
    description: "Application name (e.g., authd, api, worker)"
    required: true
  arch:
    description: "Target architecture (amd64 or arm64)"
    required: true
  semver:
    description: "Semantic version tag (e.g., v1.2.3 or 1.2.3-alpha.1). Leading 'v' is optional."
    required: true
  registry:
    description: "Container registry URL (e.g., ghcr.io)"
    required: true
  org:
    description: "Organization or namespace in the registry (e.g., hydn-co)"
    required: true
  image-prefix:
    description: "Prefix for image name (e.g., mesh-, liteiga-). Use empty string for no prefix."
    required: false
    default: "mesh-"
  branch:
    description: "Branch name for additional tag. Empty = GITHUB_REF_NAME; '-' = skip."
    required: false
    default: ""
  dockerfile-path:
    description: "Path to Dockerfile. Use {app} as placeholder."
    required: false
    default: "cmd/{app}/Dockerfile"
  build-context:
    description: "Docker build context directory"
    required: false
    default: "."

outputs:
  image:
    value: ${{ steps.outputs.outputs.image }}
  image-branch:
    value: ${{ steps.outputs.outputs.image_branch }}
  digest:
    value: ${{ steps.outputs.outputs.digest }}
  exists:
    value: ${{ steps.outputs.outputs.exists }}

runs:
  using: "composite"
  steps:
    - name: Prepare
      id: prepare
      shell: bash
      env:
        IMAGE: ${{ format('{0}/{1}/{2}{3}', inputs.registry, inputs.org, inputs.image-prefix, inputs.app) }}
        IMAGE_REF: ${{ format('{0}/{1}/{2}{3}:{4}-{5}', inputs.registry, inputs.org, inputs.image-prefix, inputs.app, inputs.semver, inputs.arch) }}
        BRANCH_INPUT: ${{ inputs.branch }}
        ARCH: ${{ inputs.arch }}
        APP: ${{ inputs.app }}
        SEMVER: ${{ inputs.semver }}
        DOCKERFILE_PATH: ${{ inputs.dockerfile-path }}
        BUILD_CONTEXT: ${{ inputs.build-context }}
      run: |
        set -euo pipefail
        [[ "$ARCH" =~ ^(amd64|arm64)$ ]] || { echo "::error::Invalid arch: $ARCH"; exit 1; }
        [[ "$SEMVER" =~ ^v?(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?(\+([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?$ ]] || { echo "::error::Invalid semver: $SEMVER"; exit 1; }
        DOCKERFILE="${DOCKERFILE_PATH//\{app\}/$APP}"
        test -f "$DOCKERFILE" || { echo "::error::Dockerfile not found: $DOCKERFILE"; exit 1; }

        B="${BRANCH_INPUT:-$GITHUB_REF_NAME}"
        if [[ "$BRANCH_INPUT" == "-" || -z "$B" ]]; then
          BT=""
        else
          BT="${B//\//-}"; BT="${BT//[^a-zA-Z0-9_.-]/-}"; BT="${BT:0:128}-$ARCH"
        fi

        docker buildx use buildx-registry-cache 2>/dev/null \
          || docker buildx create --use --name buildx-registry-cache --driver docker-container
        docker buildx inspect --bootstrap

        MANIFEST=$(docker manifest inspect "$IMAGE_REF" 2>/dev/null) || MANIFEST=""
        if [ -n "$MANIFEST" ]; then
          echo "semver_exists=true" >> "$GITHUB_OUTPUT"
          echo "image_digest=$(echo "$MANIFEST" | jq -r '.manifests[0].digest // .config.digest // empty')" >> "$GITHUB_OUTPUT"
        else
          echo "semver_exists=false" >> "$GITHUB_OUTPUT"
          echo "image_digest=" >> "$GITHUB_OUTPUT"
        fi

        echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
        echo "image_ref=$IMAGE_REF" >> "$GITHUB_OUTPUT"
        echo "branch_tag=$BT" >> "$GITHUB_OUTPUT"
        echo "dockerfile=$DOCKERFILE" >> "$GITHUB_OUTPUT"
        echo "build_context=$BUILD_CONTEXT" >> "$GITHUB_OUTPUT"

    - name: Build image
      id: build
      if: steps.prepare.outputs.semver_exists != 'true'
      shell: bash
      env:
        IMAGE_REF: ${{ steps.prepare.outputs.image_ref }}
        IMAGE: ${{ steps.prepare.outputs.image }}
        BRANCH_TAG: ${{ steps.prepare.outputs.branch_tag }}
        DOCKERFILE: ${{ steps.prepare.outputs.dockerfile }}
        BUILD_CONTEXT: ${{ steps.prepare.outputs.build_context }}
        SEMVER: ${{ inputs.semver }}
        ARCH: ${{ inputs.arch }}
      run: |
        set -euo pipefail
        ARGS=(--file "$DOCKERFILE" --platform "linux/$ARCH" --build-arg "SEMVER=$SEMVER" --tag "$IMAGE_REF")
        if [ -n "${BRANCH_TAG:-}" ]; then
          ARGS+=(--tag "$IMAGE:$BRANCH_TAG")
          ARGS+=(--cache-from "type=registry,ref=$IMAGE:$BRANCH_TAG")
          ARGS+=(--cache-to "type=registry,ref=$IMAGE:$BRANCH_TAG,mode=max")
        fi
        ARGS+=(--metadata-file /tmp/metadata.json --push "$BUILD_CONTEXT")
        docker buildx build "${ARGS[@]}"
        DIGEST=$(jq -r '."containerimage.digest" // empty' /tmp/metadata.json 2>/dev/null || echo "")
        echo "digest=${DIGEST:-}" >> "$GITHUB_OUTPUT"

    - name: Push branch tag
      if: steps.prepare.outputs.branch_tag != '' && steps.prepare.outputs.semver_exists == 'true'
      shell: bash
      continue-on-error: true
      env:
        IMAGE: ${{ steps.prepare.outputs.image }}
        IMAGE_REF: ${{ steps.prepare.outputs.image_ref }}
        BRANCH_TAG: ${{ steps.prepare.outputs.branch_tag }}
        IMAGE_DIGEST: ${{ steps.prepare.outputs.image_digest }}
      run: |
        set -euo pipefail
        REF="${IMAGE_DIGEST:-$(docker manifest inspect "$IMAGE_REF" 2>/dev/null | jq -r '.manifests[0].digest // .config.digest // empty' || echo '')}"
        [ -z "$REF" ] && exit 0
        CUR=$(docker manifest inspect "$IMAGE:$BRANCH_TAG" 2>/dev/null | jq -r '.manifests[0].digest // .config.digest // empty' || echo "")
        if [ "$CUR" != "$REF" ]; then
          docker buildx imagetools create --tag "$IMAGE:$BRANCH_TAG" "$IMAGE@$REF" \
            || echo "::warning::Failed to update branch tag $BRANCH_TAG"
        fi

    - name: Set outputs
      id: outputs
      if: always() && steps.prepare.outcome == 'success'
      shell: bash
      env:
        IMAGE_REF: ${{ steps.prepare.outputs.image_ref }}
        IMAGE: ${{ steps.prepare.outputs.image }}
        BRANCH_TAG: ${{ steps.prepare.outputs.branch_tag }}
        SEMVER_EXISTS: ${{ steps.prepare.outputs.semver_exists }}
        DIGEST: ${{ steps.prepare.outputs.semver_exists == 'true' && steps.prepare.outputs.image_digest || steps.build.outputs.digest }}
      run: |
        set -euo pipefail
        [[ -z "${IMAGE_REF:-}" ]] && { echo "::error::IMAGE_REF not set"; exit 1; }
        echo "image=$IMAGE_REF" >> "$GITHUB_OUTPUT"
        echo "image_branch=${BRANCH_TAG:+$IMAGE:$BRANCH_TAG}" >> "$GITHUB_OUTPUT"
        if [ -z "${DIGEST:-}" ]; then
          echo "::warning::Digest not available from build/prepare; falling back to manifest inspect"
          DIGEST=$(docker manifest inspect "$IMAGE_REF" 2>/dev/null | jq -r '.manifests[0].digest // .config.digest // empty' || echo "")
        fi
        echo "digest=${DIGEST:-}" >> "$GITHUB_OUTPUT"
        echo "exists=$SEMVER_EXISTS" >> "$GITHUB_OUTPUT"
