name: "Import GHCR to ACR"
description: "Imports a container image from GitHub Container Registry to Azure Container Registry"

inputs:
  org:
    description: "GitHub organization that owns the GHCR package"
    required: true
  package:
    description: "Package name in GHCR (e.g., mesh-authd)"
    required: true
  semver:
    description: "Specific tag/version to import"
    required: true
  acr_name:
    description: "Azure Container Registry short name (not FQDN)"
    required: true
  target_repo:
    description: "Target repository name in ACR (defaults to package name)"
    required: false
    default: ""
  ghcr_user:
    description: "GitHub username for GHCR authentication (e.g., github.actor)"
    required: true
  ghcr_token:
    description: "GitHub token for GHCR authentication (requires read:packages scope)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Import Image from GHCR to ACR
      shell: bash
      env:
        ORG: ${{ inputs.org }}
        PACKAGE: ${{ inputs.package }}
        SEMVER: ${{ inputs.semver }}
        ACR_NAME: ${{ inputs.acr_name }}
        TARGET_REPO: ${{ inputs.target_repo }}
        GHCR_USER: ${{ inputs.ghcr_user }}
        GHCR_TOKEN: ${{ inputs.ghcr_token }}
      run: |
        set -euo pipefail
        
        # Use package name as target repo if not specified
        if [ -z "$TARGET_REPO" ]; then
          TARGET_REPO="$PACKAGE"
        fi
        
        SOURCE="ghcr.io/$ORG/$PACKAGE:$SEMVER"
        IMAGE="$TARGET_REPO:$SEMVER"
        
        echo "📦 Checking if $ACR_NAME/$IMAGE exists..."
        
        if az acr repository show --name "$ACR_NAME" --image "$IMAGE" >/dev/null 2>&1; then
          echo "✅ Image $ACR_NAME/$IMAGE already exists, skipping import."
        else
          echo "🚀 Importing $SOURCE -> $ACR_NAME/$IMAGE"
          az acr import \
            --name "$ACR_NAME" \
            --source "$SOURCE" \
            --image "$IMAGE" \
            --username "$GHCR_USER" \
            --password "$GHCR_TOKEN"
          echo "✅ Successfully imported $ACR_NAME/$IMAGE"
        fi
