name: "Build Multi-Arch Manifest"
description: "Creates a multi-architecture image manifest from per-arch images"

inputs:
  registry:
    description: "Container registry URL (e.g., ghcr.io)"
    required: true
  org:
    description: "Organization or namespace in the registry (e.g., hydn-co)"
    required: true
  app:
    description: "Application name (e.g., authd, api, worker)"
    required: true
  semver:
    description: "Semantic version tag (e.g., v1.2.3 or 1.2.3-alpha.1). Leading 'v' is optional."
    required: true
  image-prefix:
    description: "Prefix for image name. Use empty string for no prefix."
    required: false
    default: "mesh-"
  branch:
    description: "Branch tag. Empty = GITHUB_REF_NAME, '-' = skip."
    required: false
    default: ""
  wait-for-images:
    description: "Maximum seconds to wait for arch images (0 = no wait)"
    required: false
    default: "300"

outputs:
  manifest:
    value: ${{ steps.outputs.outputs.manifest }}
  manifest-branch:
    value: ${{ steps.outputs.outputs.manifest_branch }}
  digest:
    value: ${{ steps.outputs.outputs.digest }}

runs:
  using: "composite"
  steps:
    - name: Prepare
      id: prepare
      shell: bash
      env:
        IMAGE: ${{ format('{0}/{1}/{2}{3}', inputs.registry, inputs.org, inputs.image-prefix, inputs.app) }}
        SEMVER: ${{ inputs.semver }}
        BRANCH_INPUT: ${{ inputs.branch }}
        WAIT: ${{ inputs.wait-for-images }}
      run: |
        B="${BRANCH_INPUT:-$GITHUB_REF_NAME}"; [[ "$BRANCH_INPUT" == "-" || -z "$B" ]] && BT="" || { B="${B//\//-}"; B="${B//[^a-zA-Z0-9_.-]/-}"; BT="${B:0:128}"; }
        echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
        echo "semver=$SEMVER" >> "$GITHUB_OUTPUT"
        echo "branch_tag=$BT" >> "$GITHUB_OUTPUT"
        echo "wait=$WAIT" >> "$GITHUB_OUTPUT"

    - name: Wait for arch images
      shell: bash
      env:
        IMAGE: ${{ steps.prepare.outputs.image }}
        SEMVER: ${{ steps.prepare.outputs.semver }}
        WAIT: ${{ steps.prepare.outputs.wait }}
      run: |
        DEADLINE=$(( $(date +%s) + WAIT ))
        while true; do
          MISSING=()
          for arch in amd64 arm64; do docker buildx imagetools inspect "$IMAGE:$SEMVER-$arch" &>/dev/null || MISSING+=("$arch"); done
          [[ ${#MISSING[@]} -eq 0 ]] && break
          [[ $(date +%s) -ge $DEADLINE ]] && { echo "ERROR: Missing ${MISSING[*]}"; exit 1; }
          echo "Waiting for ${MISSING[*]}..."; sleep 5
        done

    - name: Create manifest
      shell: bash
      env:
        IMAGE: ${{ steps.prepare.outputs.image }}
        SEMVER: ${{ steps.prepare.outputs.semver }}
      run: docker buildx imagetools create --tag "$IMAGE:$SEMVER" --push "$IMAGE:$SEMVER-amd64" "$IMAGE:$SEMVER-arm64"

    - name: Push branch tag
      if: steps.prepare.outputs.branch_tag != ''
      shell: bash
      env:
        IMAGE: ${{ steps.prepare.outputs.image }}
        SEMVER: ${{ steps.prepare.outputs.semver }}
        BRANCH_TAG: ${{ steps.prepare.outputs.branch_tag }}
      run: docker buildx imagetools create --tag "$IMAGE:$BRANCH_TAG" --push "$IMAGE:$SEMVER"

    - name: Set outputs
      id: outputs
      shell: bash
      env:
        IMAGE: ${{ steps.prepare.outputs.image }}
        SEMVER: ${{ steps.prepare.outputs.semver }}
        BRANCH_TAG: ${{ steps.prepare.outputs.branch_tag }}
      run: |
        echo "manifest=$IMAGE:$SEMVER" >> "$GITHUB_OUTPUT"
        echo "manifest_branch=$([ -n "$BRANCH_TAG" ] && echo "$IMAGE:$BRANCH_TAG" || echo "")" >> "$GITHUB_OUTPUT"
        echo "digest=$(docker manifest inspect "$IMAGE:$SEMVER" | jq -r '.manifests[0].digest // .config.digest // empty')" >> "$GITHUB_OUTPUT"
