name: "Build Multi-Arch Manifest"
description: "Creates a multi-architecture image manifest from per-arch images"

inputs:
  registry:
    description: "Container registry URL (e.g., ghcr.io)"
    required: true
  org:
    description: "Organization or namespace in the registry (e.g., hydn-co)"
    required: true
  app:
    description: "Application name (e.g., authd, api, worker)"
    required: true
  semver:
    description: "Semantic version tag (e.g., v1.2.3 or 1.2.3-alpha.1). Leading 'v' is optional."
    required: true
  image-prefix:
    description: "Prefix for image name. Use empty string for no prefix."
    required: false
    default: "mesh-"
  architectures:
    description: "Comma-separated target architectures"
    required: false
    default: "amd64,arm64"
  branch:
    description: "Branch tag. Empty = GITHUB_REF_NAME, '-' = skip."
    required: false
    default: ""
  wait-for-images:
    description: "Maximum seconds to wait for arch images (0 = check once without retrying)"
    required: false
    default: "300"

outputs:
  manifest:
    value: ${{ steps.outputs.outputs.manifest }}
  manifest-branch:
    value: ${{ steps.outputs.outputs.manifest_branch }}
  digest:
    value: ${{ steps.outputs.outputs.digest }}

runs:
  using: "composite"
  steps:
    - name: Prepare
      id: prepare
      shell: bash
      env:
        IMAGE: ${{ format('{0}/{1}/{2}{3}', inputs.registry, inputs.org, inputs.image-prefix, inputs.app) }}
        SEMVER: ${{ inputs.semver }}
        ARCHITECTURES: ${{ inputs.architectures }}
        BRANCH_INPUT: ${{ inputs.branch }}
        WAIT: ${{ inputs.wait-for-images }}
      run: |
        set -euo pipefail
        [[ "$SEMVER" =~ ^v?(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?(\+([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?$ ]] \
          || { echo "::error::Invalid semver: $SEMVER"; exit 1; }

        IFS=',' read -ra ARCHES <<< "$ARCHITECTURES"
        [[ ${#ARCHES[@]} -ge 2 ]] || { echo "::error::At least 2 architectures required, got: $ARCHITECTURES"; exit 1; }

        B="${BRANCH_INPUT:-$GITHUB_REF_NAME}"
        if [[ "$BRANCH_INPUT" == "-" || -z "$B" ]]; then
          BT=""
        else
          BT="${B//\//-}"; BT="${BT//[^a-zA-Z0-9_.-]/-}"; BT="${BT:0:128}"
        fi

        echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
        echo "semver=$SEMVER" >> "$GITHUB_OUTPUT"
        echo "architectures=$ARCHITECTURES" >> "$GITHUB_OUTPUT"
        echo "branch_tag=$BT" >> "$GITHUB_OUTPUT"
        echo "wait=$WAIT" >> "$GITHUB_OUTPUT"

    - name: Wait for arch images
      shell: bash
      env:
        IMAGE: ${{ steps.prepare.outputs.image }}
        SEMVER: ${{ steps.prepare.outputs.semver }}
        ARCHITECTURES: ${{ steps.prepare.outputs.architectures }}
        WAIT: ${{ steps.prepare.outputs.wait }}
      run: |
        set -euo pipefail
        IFS=',' read -ra ARCHES <<< "$ARCHITECTURES"
        DEADLINE=$(( $(date +%s) + WAIT ))
        while true; do
          MISSING=()
          for arch in "${ARCHES[@]}"; do
            docker buildx imagetools inspect "$IMAGE:$SEMVER-$arch" &>/dev/null || MISSING+=("$arch")
          done
          [[ ${#MISSING[@]} -eq 0 ]] && break
          if [[ $(date +%s) -ge $DEADLINE ]]; then
            echo "::error::Timed out waiting for arch images: ${MISSING[*]}"
            exit 1
          fi
          echo "Waiting for ${MISSING[*]}..."
          sleep 5
        done

    - name: Create manifest
      shell: bash
      env:
        IMAGE: ${{ steps.prepare.outputs.image }}
        SEMVER: ${{ steps.prepare.outputs.semver }}
        ARCHITECTURES: ${{ steps.prepare.outputs.architectures }}
      run: |
        set -euo pipefail
        IFS=',' read -ra ARCHES <<< "$ARCHITECTURES"
        SOURCES=()
        for arch in "${ARCHES[@]}"; do SOURCES+=("$IMAGE:$SEMVER-$arch"); done
        docker buildx imagetools create --tag "$IMAGE:$SEMVER" "${SOURCES[@]}"

    - name: Push branch tag
      if: steps.prepare.outputs.branch_tag != ''
      shell: bash
      continue-on-error: true
      env:
        IMAGE: ${{ steps.prepare.outputs.image }}
        SEMVER: ${{ steps.prepare.outputs.semver }}
        BRANCH_TAG: ${{ steps.prepare.outputs.branch_tag }}
      run: |
        set -euo pipefail
        docker buildx imagetools create --tag "$IMAGE:$BRANCH_TAG" "$IMAGE:$SEMVER" \
          || echo "::warning::Failed to update branch tag $BRANCH_TAG"

    - name: Set outputs
      id: outputs
      if: always() && steps.prepare.outcome == 'success'
      shell: bash
      env:
        IMAGE: ${{ steps.prepare.outputs.image }}
        SEMVER: ${{ steps.prepare.outputs.semver }}
        BRANCH_TAG: ${{ steps.prepare.outputs.branch_tag }}
      run: |
        set -euo pipefail
        echo "manifest=$IMAGE:$SEMVER" >> "$GITHUB_OUTPUT"
        echo "manifest_branch=${BRANCH_TAG:+$IMAGE:$BRANCH_TAG}" >> "$GITHUB_OUTPUT"
        DIGEST="sha256:$(docker buildx imagetools inspect --raw "$IMAGE:$SEMVER" 2>/dev/null | sha256sum | awk '{print $1}')" || DIGEST=""
        [[ "$DIGEST" == "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" ]] && DIGEST=""
        echo "digest=${DIGEST:-}" >> "$GITHUB_OUTPUT"
