name: "Deploy Bicep Template"
description: "Deploys Azure Bicep template using subscription-scoped deployment"

inputs:
  environment:
    description: "Target environment name (e.g., dev1, prod1)"
    required: true
  name:
    description: "Deployment name (will be suffixed with environment)"
    required: true
  semver:
    description: "Semantic version to deploy"
    required: true
  applyCerts:
    description: "Whether to apply certificates (true/false)"
    required: false
    default: "false"
  location:
    description: "Azure region for deployment metadata"
    required: false
    default: "eastus"
  template:
    description: "Path to Bicep template file"
    required: false
    default: "./.deploy/bicep/main.bicep"
  parameters:
    description: "Path to Bicep parameters file (will append environment if not full path)"
    required: false
    default: "./.deploy/bicep/parameters"

runs:
  using: "composite"
  steps:
    - name: Deploy Bicep Template
      shell: bash
      env:
        NAME: ${{ inputs.name }}-${{ inputs.environment }}
        LOCATION: ${{ inputs.location }}
        TEMPLATE: ${{ inputs.template }}
        PARAMETERS: ${{ inputs.parameters }}
        ENVIRONMENT: ${{ inputs.environment }}
        APPLY_CERTS: ${{ inputs.applyCerts }}
        SEMVER: ${{ inputs.semver }}
      run: |
        set -euo pipefail
        
        # Determine parameters file path
        if [[ "$PARAMETERS" == *.bicepparam ]]; then
          PARAMS_FILE="$PARAMETERS"
        else
          PARAMS_FILE="${PARAMETERS}/${ENVIRONMENT}.bicepparam"
        fi
        
        echo "🚀 Deploying Bicep template"
        echo "  Name: $NAME"
        echo "  Location: $LOCATION"
        echo "  Template: $TEMPLATE"
        echo "  Parameters: $PARAMS_FILE"
        echo "  Version: $SEMVER"
        echo "  Apply Certs: $APPLY_CERTS"
        
        az deployment sub create \
          --name "$NAME" \
          --location "$LOCATION" \
          --template-file "$TEMPLATE" \
          --parameters "$PARAMS_FILE" \
            applyCerts="$APPLY_CERTS" \
            semver="$SEMVER"
        
        echo "✅ Deployment completed successfully"
